version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Dependencies required to build your docs
python:
   install:
   - requirements: docs/doc_requirements.txt

