[tool.black]
exclude = "dug_seis/graphical_interface/ui_files"

[tool.pytest.ini_options]
# Ignore the aurem tests for now.
addopts = '--ignore=dug_seis/event_processing/picking/pickers/aurem/tests/test_aurem.py'
filterwarnings = [
    'ignore:.*`np.long` is a deprecated alias for `np.compat.long`*',
    'ignore:.*`np.int` is a deprecated alias for the builtin `int`*',
    'ignore:.*`np.bool` is a deprecated alias for the builtin `bool`*',
    'ignore:.*Using or importing the ABCs from *'
]